spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/cineapp
    username: postgres
    password: 123
    # driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://${host}/${database}
    # username: ${username}
    # password: ${password}
        
server:
   port: 8080        
   
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
      
#para seguridad      
security:
   oauth2:
    resource:
      userInfoUri: ${hostapi}    